#! /bin/sh

sxhkd &

bspc config border_width        1
bspc config window_gap         10
bspc config top_padding        22
bspc config left_padding       0
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true
bspc config normal_border_color "#333333"
bspc config active_border_color "#2d2d2d"
bspc config focused_border_color "#2d2d2d"
bspc config presel_border_color "#2d2d2d"
bspc config urgent_border_color "#d64937"
bspc config focused_locked_border_color "#f9f9f9"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1
bspc config focus_follows_pointer true

bspc monitor -d 1 2 3 4 5

bspc rule -a Steam desktop=^3 follow=on split_dir=right
bspc rule -a Gimp desktop=^5 follow=on

## autostart
unclutter -root -idle 10 &
feh --bg-scale /home/infosec/Pictures/poly3.png &
compton --shadow-exclude 'n:a:Conky' -b &
cd /home/infosec/.config/bspwm/panel/ && ./panel &
